baseURL = "https://www.andrewszot.com"
languageCode = "en-us"
title = "Andrew Szot"
theme = "loveit"
[params]
  # LoveIt theme version
  version = "0.2.X"
  [params.page]
    [params.page.math]
        enable = true

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/posts/"
    title = "Blog"
    weight = 1
	[[menu.main]]
    identifier = "GitHub"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "GitHub"
    url = "https://github.com/aszot"
    title = ""
    weight = 1

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

