baseURL = "https://www.andrewszot.com"
languageCode = "en-us"
title = "Andrew Szot"
theme = "loveit"
[params]
  # LoveIt theme version
  version = "0.2.X"
  [params.page]
    [params.page.math]
        enable = true
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      keepStatic = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = false

[menu]
  [[menu.main]]
    identifier = "cv"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "CV"
    url = "/landing/personal_cv.pdf"
    title = "CV"
    weight = 1
  [[menu.main]]
    identifier = "scholar"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Scholar"
    url = "https://scholar.google.com/citations?hl=en&user=IwIWKPYAAAAJ"
    title = "Scholar"
    weight = 1
  [[menu.main]]
    identifier = "GitHub"
    pre = ""
    post = ""
    name = "GitHub"
    url = "https://github.com/aszot"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts"
    title = "Posts"
    weight = 1

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

